# Generated by Django 5.0.4 on 2024-04-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubType',
            fields=[
                ('sub_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.IntegerField(primary_key=True, serialize=False)),
                ('album_release_date', models.DateField()),
                ('album_name', models.CharField(max_length=30)),
                ('album_length', models.IntegerField(null=True)),
                ('album_song_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=30)),
                ('artist_note', models.CharField(max_length=1000)),
                ('artist_next_tour', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('category_song_count', models.IntegerField(null=True)),
                ('category_playlist_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
                ('creation_date', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('last_payment_date', models.DateField(null=True)),
                ('next_payment_date', models.DateField(null=True)),
                ('acc_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.accountsubtype')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLikedAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.account')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.artist'),
        ),
        migrations.CreateModel(
            name='AccountFollowedArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.account')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.artist')),
            ],
        ),
        migrations.CreateModel(
            name='FollowedAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.account')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=30)),
                ('playlist_create_date', models.DateField()),
                ('playlist_note', models.CharField(max_length=30, null=True)),
                ('playlist_length', models.IntegerField(null=True)),
                ('playlist_song_count', models.IntegerField(null=True)),
                ('playlist_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify.category')),
            ],
        ),
        migrations.CreateModel(
            name='AccountFollowedPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.account')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=30)),
                ('song_length', models.IntegerField()),
                ('song_played_count', models.IntegerField(null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.album')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.category')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLikedSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.account')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.song')),
            ],
        ),
        migrations.CreateModel(
            name='SongsInPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.song')),
            ],
        ),
    ]
