# Generated by Django 5.0.4 on 2024-04-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowedAlbums',
            new_name='AccountFollowedAlbums',
        ),
        migrations.RemoveField(
            model_name='accountlikedsongs',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountlikedsongs',
            name='song',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_length',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_song_count',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='next_payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountsubtype',
            name='sub_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_song_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_next_tour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_playlist_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_song_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotify.category'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_note',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_played_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AccountLikedAlbums',
        ),
        migrations.DeleteModel(
            name='AccountLikedSongs',
        ),
    ]
